spin_manifest_version = 2

[application]
name = "edge-native-use-cases"
version = "0.1.0"
authors = ["Akamai Developers <thans@akamai.com>"]
description = ""

[variables]
greeting = { default = "Hello" }

[[trigger.http]]
route = "/api/..."
component = "api"

[[trigger.http]]
route = "/frontend/..."
component = "frontend"

[component.api]
source = "api/target/wasm32-wasip1/release/api.wasm"
allowed_outbound_hosts = []
key_value_stores = [ "default"]

[component.api.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "api"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.api.variables]
greeting = "{{ greeting }}"

[component.frontend]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "frontend", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }
