spin_manifest_version = 2

[application]
authors = ["Akamai Developers <thans@akamai.com>"]
description = ""
name = "edge-native-use-cases"
version = "0.1.0"

[variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications

[[trigger.http]]
route = "/..."
component = "edge-native-use-cases"

[component.edge-native-use-cases]
source = "dist/edge-native-use-cases.wasm"
exclude_files = ["**/node_modules"]
# Outbound HTTP requests
# See https://spinframework.dev/v3/http-outbound#granting-http-permissions-to-components
allowed_outbound_hosts = []

# Key Value Stores 
# See https://spinframework.dev/v3/kv-store-api-guide#granting-key-value-store-permissions-to-components
key_value_stores = []

[component.edge-native-use-cases.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]

[component.edge-native-use-cases.variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications