spin_manifest_version = 2

[application]
name = "edge-native-use-cases"
version = "0.1.0"
authors = ["Akamai Developers <thans@akamai.com>"]
description = ""

[variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "api/target/wasm32-wasip1/release/api.wasm"
# Outbound HTTP requests
# See https://spinframework.dev/v3/http-outbound#granting-http-permissions-to-components
allowed_outbound_hosts = []
# Key Value Stores 
# See https://spinframework.dev/v3/kv-store-api-guide#granting-key-value-store-permissions-to-components
key_value_stores = []

[component.api.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "api"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.api.variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications