#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "hol2-edgenative-usecases"
version = "0.1.0"
authors = ["Akamai Developers <thans@akamai.com>"]
description = ""

[variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications

[[trigger.http]]
route = "/..."
component = "hol2-edgenative-usecases"

[component.hol2-edgenative-usecases]
source = "target/wasm32-wasip1/release/hol2_edgenative_usecases.wasm"
# Outbound HTTP requests
# See https://spinframework.dev/v3/http-outbound#granting-http-permissions-to-components
allowed_outbound_hosts = []

# Key Value Stores 
# See https://spinframework.dev/v3/kv-store-api-guide#granting-key-value-store-permissions-to-components
key_value_stores = []

[component.hol2-edgenative-usecases.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.hol2-edgenative-usecases.variables]
# See https://spinframework.dev/v3/variables#adding-variables-to-your-applications